services:
  - type: web
    name: kronilo
    staticPublishPath: ./dist
    buildCommand: npm run build
    headers:
      - path: /*
        name: Content-Security-Policy
        value: default-src 'self'; script-src 'self'; object-src 'none'; base-uri 'self'; frame-ancestors 'none'
      - path: /*
        name: Strict-Transport-Security
        value: max-age=63072000; includeSubDomains; preload
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /*
        name: X-Frame-Options
        value: DENY
      - path: /*
        name: Referrer-Policy
        value: strict-origin-when-cross-origin
      - path: /*
        name: Cross-Origin-Resource-Policy
        value: same-origin
      - path: /*
        name: Cross-Origin-Embedder-Policy
        value: require-corp
      - path: /*
        name: Cross-Origin-Opener-Policy
        value: same-origin
      - path: /*
        name: Permissions-Policy
        value: accelerometer=(), autoplay=(), camera=(), geolocation=(), gyroscope=(), magnetometer=(), microphone=(), payment=(), usb=(), speaker=()
      - path: /assets/*.html
        name: Cache-Control
        value: no-cache, must-revalidate
      - path: /assets/*.js
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /assets/*.css
        name: Cache-Control
        value: public, max-age=31536000, immutable
